language: java
sudo: false
jdk:
- oraclejdk8
install: true
branches:
  only:
  - master
script: mvn install jacoco:report coveralls:report

before_deploy:
  - "mvn -DskipTests package"
  - export FOO=$(find /home/travis/.m2/repository/com/jivesoftware/os/mlogger/*  -type f)
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: iP7Jle8DWOyp+fTf7N+OfFmcMzASE6clKSTxnGND169OLuYMVjPI4xmNlYHvef4LOCMSTfcwrlozH40S0BuEFAk2ZrouCs4oUvjWc3W59hxlDxn0ufZb6mRA+uF49gRrcTi+uV55kwqT5kn/OfjEchZJVwuwdgbjY/3rHAftf+4=
  file: "${FOO}"
  on:
    repo: jivesoftware/mlogger
